"""Initial migration

Revision ID: 00fedff99823
Revises: eff1a5e51aa7
Create Date: 2024-02-19 14:38:12.384592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fedff99823'
down_revision: Union[str, None] = 'eff1a5e51aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=320),
               existing_nullable=True)
    # ### end Alembic commands ###
