"""Initial migration

Revision ID: 48ea00d99ec8
Revises: 4e9b099212c5
Create Date: 2024-02-15 15:37:55.513573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ea00d99ec8'
down_revision: Union[str, None] = '4e9b099212c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_goods', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_goods'], ['goods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    # ### end Alembic commands ###
