"""Initial migration

Revision ID: 9af8ef4508bc
Revises: aa2514c4186d
Create Date: 2024-02-13 15:57:47.427363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af8ef4508bc'
down_revision: Union[str, None] = 'aa2514c4186d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goods_stars_fkey', 'goods', type_='foreignkey')
    op.drop_column('goods', 'stars')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('goods_stars_fkey', 'goods', 'reviews', ['stars'], ['id'])
    # ### end Alembic commands ###
