"""Initial migration

Revision ID: ab2d92a28167
Revises: e9762801b50b
Create Date: 2024-02-12 13:22:28.297609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2d92a28167'
down_revision: Union[str, None] = 'e9762801b50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.drop_constraint('goods_tag_fkey', 'goods', type_='foreignkey')
    op.create_foreign_key(None, 'goods', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('goods', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.create_foreign_key('goods_tag_fkey', 'goods', 'tags', ['tag'], ['id'], ondelete='CASCADE')
    op.drop_column('goods', 'tag_id')
    # ### end Alembic commands ###
