"""Initial migration

Revision ID: af5d13cdf9f5
Revises: 270eeb00bf47
Create Date: 2024-02-11 19:47:48.939714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5d13cdf9f5'
down_revision: Union[str, None] = '270eeb00bf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('new_description', sa.String(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_constraint('tags_type_goods_key', 'tags', type_='unique')
    op.drop_column('tags', 'type_goods')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('type_goods', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('tags_type_goods_key', 'tags', ['type_goods'])
    op.drop_table('goods')
    # ### end Alembic commands ###
