"""Initial migration

Revision ID: e0e147571747
Revises: 09af0eddc699
Create Date: 2024-02-13 15:52:00.107209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e147571747'
down_revision: Union[str, None] = '09af0eddc699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('stars', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'goods', 'reviews', ['stars'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.drop_column('goods', 'stars')
    # ### end Alembic commands ###
