"""Initial migration

Revision ID: e9762801b50b
Revises: af5d13cdf9f5
Create Date: 2024-02-11 19:55:17.616448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9762801b50b'
down_revision: Union[str, None] = 'af5d13cdf9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag', sa.String(), nullable=False))
    op.drop_constraint('tags_teg_key', 'tags', type_='unique')
    op.create_unique_constraint(None, 'tags', ['tag'])
    op.drop_column('tags', 'teg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('teg', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_unique_constraint('tags_teg_key', 'tags', ['teg'])
    op.drop_column('tags', 'tag')
    # ### end Alembic commands ###
