"""Initial migration

Revision ID: f073dc923ca8
Revises: 84ed1c81c69e
Create Date: 2024-02-19 14:04:30.555215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f073dc923ca8'
down_revision: Union[str, None] = '84ed1c81c69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('image_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'image_path')
    # ### end Alembic commands ###
